#!/usr/bin/env bash
# Usage $0 package-name
# For example, $0 core
js_root=$(git rev-parse --show-toplevel)
pkg_root=${js_root}/pkg/cloudinary-${1}

if [ ! -d ${js_root} ]; then
    echo "Root folder ${pkg_root} does not exist!"
    exit 1
fi

if [ ! -d ${pkg_root} ]; then
    echo "Package folder ${pkg_root} does not exist!"
    exit 1
fi

cd ${pkg_root} &&
npm publish
