// Generated by CoffeeScript 1.9.1
var Cloudinary;

Cloudinary = (function() {
  var build_array, option_consume;

  function Cloudinary() {}

  option_consume = function(options, option_name, default_value) {
    var result;
    result = options[option_name];
    delete options[option_name];
    if (typeof result === 'undefined') {
      return default_value;
    } else {
      return result;
    }
  };

  build_array = function(arg) {
    if (arg === null || typeof arg === 'undefined') {
      return [];
    } else if ($.isArray(arg)) {
      return arg;
    } else {
      return [arg];
    }
  };

  return Cloudinary;

})();

//# sourceMappingURL=cloudinarymethods.js.map
